---
title: "HABS data"
author: "Richard Arnold"
date: '2023-11-23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warn=FALSE, message=FALSE)
```

```{r}
load("opar.Rda")
library(dplyr)
library(tidyverse)
library(tidyr)
library(readxl)
library(ggplot2)
library(maps)
library(sf)
library(geojsonsf)
library(rmapshaper)

library(algae)
source("funcs.R")
source("maps.R")
```
```{r}
bbox.marlselect <- c(1645,5415,1720,5495)*1000
bbox.marlselect <- c(1645,5412,1725,5502)*1000
xlim.marlselect <- bbox.marlselect[c(1,3)]
ylim.marlselect <- bbox.marlselect[c(2,4)]

xlim.havelock <- c(1660,1675)*1000
ylim.havelock <- c(5425,5440)*1000

xlim.arapawa <- c(1695,1718)*1000
ylim.arapawa <- c(5432,5452)*1000

bbox.marlselect.polygon <- st_polygon(list(cbind(bbox.marlselect[c(1,3,3,1,1)],
                                                 bbox.marlselect[c(2,2,4,4,2)])))
coast.marlselect <- st_crop(coast, bbox.marlselect.polygon)
```

```{r}
coast.marlselect
coast.arapawa <- coast.marlselect %>% filter(str_detect(name, "Arapawa"))
coast.arasi <- coast.marlselect %>% filter(str_detect(name, "Arapawa") | str_detect(name, "Waipounamu"))
coast.si <- coast.marlselect %>% filter(str_detect(name, "Waipounamu"))
coast.arapawa
coast.arasi
coast.si
```

```{r}
for(i in 1:nrow(coast.marlselect)) {
  plot(st_geometry(coast.marlselect[i,]), col="darkgreen", xlim=xlim.marlselect, ylim=ylim.marlselect)
  title(paste(i,coast.marlselect$name[i]))
}

```



```{r}
list.files("data/")
```


```{r}
habspoly_sf <- geojson_sf("data/HABS_exp_6_release_polygons.geojson")
habspoly_sf <- st_transform(habspoly_sf, crs=st_crs(coast))
#marlpoly_sf <- geojson_sf("data/Entire_marlb_polygons.geojson")
marlpoly_sf <- geojson_sf("data/Entire_marlb_polygons_volume.geojson")
marlpoly_sf <- st_transform(marlpoly_sf, crs=st_crs(coast))
#plot(habspoly_sf)
#ggplot(geo) + geom_sf(aes(fill = SA2_NAME)) + guides(fill = guide_none())
```

Just a small number of key polygons

```{r}
plot(coast.marlselect$geometry, col="dark green", xlim=xlim.marlselect, ylim=ylim.marlselect); box()
rect(xlim.marlselect[1], ylim.marlselect[1], xlim.marlselect[2], ylim.marlselect[2])
plot(st_geometry(habspoly_sf), col="yellow", add=TRUE)
plot(st_geometry(st_centroid(habspoly_sf)), pch="+", col="red", cex=0.7, add=TRUE)
#box(); axis(1); axis(2)
```

Full tiling of Marlborough

```{r}
plot(coast.marlselect$geometry, col="dark green", xlim=xlim.marlselect, ylim=ylim.marlselect); box()
rect(xlim.marlselect[1], ylim.marlselect[1], xlim.marlselect[2], ylim.marlselect[2])
plot(st_geometry(marlpoly_sf), col="yellow", add=TRUE)
plot(st_geometry(st_centroid(marlpoly_sf)), pch="+", col="red", cex=0.7, add=TRUE)
#box(); axis(1); axis(2)
#rect(1660*1000, 5425*1000, 1675*1000, 5440*1000, border="red", lwd=2)
```

Zoom in to area near Havelock and Mahau Sound

```{r}
plot(coast.marlselect$geometry, col="dark green", xlim=xlim.havelock, ylim=ylim.havelock); box()
rect(xlim.marlselect[1], ylim.marlselect[1], xlim.marlselect[2], ylim.marlselect[2])
plot(st_geometry(marlpoly_sf), col="yellow", add=TRUE)
plot(st_geometry(st_centroid(marlpoly_sf)), pch="+", col="red", cex=0.7, add=TRUE)
rect(xlim.havelock[1], ylim.havelock[1], xlim.havelock[2], ylim.havelock[2], border="red")
box(); axis(1); axis(2)
#rect(1660*1000, 5425*1000, 1675*1000, 5440*1000, border="red", lwd=2)
```

```{r}
# check coordinate reference system CRS
#st_crs(marlpoly_sf)
st_crs(marlpoly_sf) == st_crs(coast.marlselect)
```

Zoom into area around Arapawa Island

```{r}
plot(coast.marlselect$geometry, col="darkgreen")
plot((coast.marlselect %>% filter(str_detect(name, "Arapawa")))$geometry, col="darkgreen")
```

```{r}
plot(coast.arapawa$geometry, col="darkgreen")

sta <- st_intersects(marlpoly_sf, coast.arapawa)
marlpoly.arapawa <- marlpoly_sf[lengths(sta)>0,]
plot(coast.arapawa$geometry, col="darkgreen")
plot(marlpoly.arapawa$geometry, col="yellow", add=TRUE)
title("Original polygons")

#marlpoly.arapawa.trim <- st_difference(marlpoly.arapawa, coast.arapawa)
marlpoly.arapawa.trim <- ms_erase(marlpoly.arapawa, coast.arapawa)
plot(coast.arapawa$geometry, col="darkgreen")
plot(marlpoly.arapawa.trim$geometry, col="yellow", add=TRUE)
title("Trimmed polygons")

stx <- st_crosses(marlpoly.arapawa.trim, coast.arapawa)
all(sapply(stx,length)==0) # TRUE - the objects are touching or disjoint
```


```{r}
plot(coast.arapawa$geometry, col="darkgreen"); plot(marlpoly_sf$geometry, add=TRUE, col="#00007722")
plot(ms_erase(coast.arapawa, marlpoly_sf)$geometry, col="darkgreen"); plot(marlpoly_sf$geometry, add=TRUE)
plot(ms_erase(marlpoly_sf, coast.arapawa)$geometry, col="yellow", xlim=xlim.arapawa, ylim=ylim.arapawa) 
plot(ms_erase(marlpoly_sf, coast.marlselect)$geometry, col="yellow", xlim=xlim.arapawa, ylim=ylim.arapawa) 
#plot(st_difference(coast.arapawa, marlpoly_sf)$geometry, col="darkgreen"); plot(marlpoly_sf$geometry, add=TRUE)
#plot(st_difference(marlpoly_sf, coast.arapawa)$geometry, col="yellow", xlim=xlim.arapawa, ylim=ylim.arapawa) 
#plot(st_difference(marlpoly_sf, coast.marlselect)$geometry, col="yellow", xlim=xlim.arapawa, ylim=ylim.arapawa) 
```

South Island mainland

```{r}
plot(coast.si$geometry, col="darkgreen")

sta <- st_intersects(marlpoly_sf, coast.si)
marlpoly.si <- marlpoly_sf[lengths(sta)>0,]
plot(coast.si$geometry, col="darkgreen")
plot(marlpoly.si$geometry, col="yellow", add=TRUE)
title("Original polygons")

#marlpoly.si.trim <- st_difference(marlpoly.si, coast.si)
marlpoly.si.trim <- ms_erase(marlpoly.si, coast.si)
plot(coast.si$geometry, col="darkgreen")
plot(marlpoly.si.trim$geometry, col="yellow", add=TRUE)
title("Trimmed polygons")

#marlpoly.si.trim <- st_difference(marlpoly.si, coast.si)
marlpoly.si.trim <- ms_erase(marlpoly.si, coast.si)
plot(coast.si$geometry, col="darkgreen", xlim=xlim.havelock, ylim=ylim.havelock)
plot(marlpoly.si.trim$geometry, col="yellow", add=TRUE)
title("Trimmed polygons")

stx <- st_crosses(marlpoly.si.trim, coast.si)
all(sapply(stx,length)==0) # TRUE - the objects are touching or disjoint
```


South Island mainland + Arapawa Island

```{r}
plot(coast.arasi$geometry, col="darkgreen")

sta <- st_intersects(marlpoly_sf, coast.arasi)
marlpoly.arasi <- marlpoly_sf[lengths(sta)>0,]
plot(coast.arasi$geometry, col="darkgreen")
plot(marlpoly.arasi$geometry, col="yellow", add=TRUE)
title("Original polygons")

#marlpoly.arasi.trim <- st_difference(marlpoly.arasi, coast.arasi)
marlpoly.arasi.trim <- ms_erase(marlpoly.arasi, coast.arasi)
plot(coast.arasi$geometry, col="darkgreen")
plot(marlpoly.arasi.trim$geometry, col="yellow", add=TRUE)
title("Trimmed polygons")

#marlpoly.arasi.trim <- st_difference(marlpoly.arasi, coast.arasi)
marlpoly.arasi.trim <- ms_erase(marlpoly.arasi, coast.arasi)
plot(coast.arasi$geometry, col="darkgreen", xlim=xlim.havelock, ylim=ylim.havelock)
plot(marlpoly.arasi.trim$geometry, col="yellow", add=TRUE)
title("Trimmed polygons")

stx <- st_crosses(marlpoly.arasi.trim, coast.arasi)
all(sapply(stx,length)==0) # TRUE - the objects are touching or disjoint
```

```{r}
nrow(marlpoly_sf) # 408
nrow(marlpoly_sf.trim) # 408
nrow(marlpoly.arasi) # 213
nrow(marlpoly.arasi.trim) # 213
nrow(marlpoly.si) # 196
nrow(marlpoly.si.trim) # 196
```

Find only those parts of the tiling polygons that are not on land

```{r}
#xx <- st_intersection(marlpoly_sf, coast.marlselect)
#marlpoly_sf.trim <- st_difference(marlpoly_sf, coast.marlselect)  ## 18768 features
marlpoly_sf.trim <- ms_erase(marlpoly_sf, coast.marlselect)  ## 18768 features
#st_is_valid(xx)
##x2 <- st_difference(coast.marlselect, marlpoly_sf)
```

Check for any intersection
```{r}
# this is slow
#stx <- st_crosses(marlpoly_sf.trim, coast.marlselect)
#all(sapply(stx,length)==0) # TRUE - the objects are touching or disjoint
```



```{r}
coast.marlselect # 46 features
marlpoly_sf # 408 features
is.unique(marlpoly_sf$CLUSTER_ID) # TRUE
is.unique(marlpoly_sf.trim$CLUSTER_ID) # TRUE
```


```{r}
plot(st_geometry(coast.marlselect), xlim=xlim.arapawa, ylim=ylim.arapawa, col="darkgreen")
plot(st_geometry(marlpoly_sf), xlim=xlim.arapawa, ylim=ylim.arapawa, col="yellow")
plot(st_geometry(marlpoly_sf.trim), xlim=xlim.arapawa, ylim=ylim.arapawa, col="yellow")
plot(st_geometry(coast.arapawa), col="darkgreen")
plot(st_geometry(marlpoly.arapawa), col="yellow")
plot(st_geometry(marlpoly.arapawa.trim), col="yellow")
```


```{r}
plot(st_geometry(coast.marlselect), xlim=xlim.havelock, ylim=ylim.havelock, col="darkgreen")
plot(st_geometry(marlpoly_sf), xlim=xlim.havelock, ylim=ylim.havelock, col="yellow")
plot(st_geometry(marlpoly_sf.trim), xlim=xlim.havelock, ylim=ylim.havelock, col="yellow")
```


```{r, warn=FALSE, message=FALSE}
plot(coast.marlselect$geometry, col="dark green", xlim=xlim.havelock, ylim=ylim.havelock); box()
plot(st_geometry(marlpoly_sf.trim), col="yellow", add=TRUE)
plot(st_geometry(st_centroid(marlpoly_sf.trim)), pch="+", col="red", cex=0.7, add=TRUE)
plot(st_geometry(coast.marlselect), col=NA, border="blue", add=TRUE)
```

```{r, warn=FALSE, message=FALSE}
plot(st_geometry(marlpoly_sf), xlim=xlim.havelock, ylim=ylim.havelock, col="#44000022")
plot(st_geometry(st_centroid(marlpoly_sf)), pch="+", col="red", cex=0.7, add=TRUE)
plot(st_geometry(coast.marlselect), col="#00440022", border="blue", add=TRUE)
```


```{r, warn=FALSE, message=FALSE}
plot(st_geometry(marlpoly_sf), xlim=xlim.havelock, ylim=ylim.havelock)
plot(st_geometry(st_centroid(marlpoly_sf)), pch="+", col="red", cex=0.7, add=TRUE)
plot(st_geometry(coast.marlselect), col=NA, border="blue", add=TRUE)
plot(st_geometry(marlpoly_sf.trim), border="green", add=TRUE)
plot(st_geometry(st_centroid(marlpoly_sf.trim)), pch="x", col="orange", add=TRUE)
```

```{r}
plot(coast.marlselect$geometry, col="dark green", xlim=xlim.havelock, ylim=ylim.havelock); box()
plot(st_geometry(marlpoly_sf.trim), col="yellow", add=TRUE)
plot(st_geometry(st_centroid(marlpoly_sf.trim)), pch="+", col="red", cex=0.7, add=TRUE)
```


Presence Absence data
```{r}
#list.files("data/")
habswide <- read_excel("data/HABs_synthetic_dataset_presence_absence.xlsx")
habswide$ID <- as.numeric(habswide$ID)
#habswide[1:3,]
#range(habswide$ID,na.rm=TRUE) # 1 40
#habswide[is.na(habswide$ID),]
#habswide$Name

habssites <- habswide[,c("ID","Name")]
habssites <- habssites[order(habssites$ID),]

habs <- pivot_longer(habswide, cols=names(habswide)[-(1:2)], names_to="date", values_to="present")
habs$date <- gsub("'","",habs$date)
habs$date <- as.Date(habs$date, format="%d-%b-%Y")
#habs[1:5,]
```

```{r}
par(opar)
par(mar=c(5.1,10.1,4.1,2.1))
nsites <- max(habssites$ID,na.rm=TRUE)
idx <- habs$present==1
plot(habs$date[idx], habs$ID[idx], pch=16, cex=0.4,
     axes=FALSE, xlab="Date", ylab="", main="2018")
axis.Date(1, range(habs$date[idx]), format="%d-%b"); 
axis(2,las=2,at=1:nsites, habssites$Name[1:nsites], cex.axis=0.3); box()
par(opar)
```

Connection and migration matrices
```{r}
list.files("data/")
#fname <- "data/Connectivity_matrices_04_to_07_2018.xlsx"
fname <- "data/connectivity_matrix.xlsx"
nsheets <- length(excel_sheets(fname))
conn <- lapply(1:nsheets, function(i) read_excel(fname, sheet=i, col_names=FALSE))
names(conn) <- excel_sheets(fname)

#fname <- "data/Migration_matrices_04_to_07_2018.xls"
fname <- "data/migration_matrix.xlsx"
nsheets <- length(excel_sheets(fname))
migr <- lapply(1:nsheets, function(i) read_excel(fname, sheet=i, col_names=FALSE))
names(migr) <- excel_sheets(fname)
matdates <- as.Date(names(migr),format="%Y%m%d")
```

```{r}
# rows are sources, columns are receiving locations
sapply(conn, dim) # all 408 by 408
sapply(migr, dim) # all 408 by 408
# conn is the gives the proportion of particles form the source that end up in the receiving polygon
# if this were a complete tiling of the area then the row sums would be 1
sapply(conn, function(x) range(apply(x,1,sum,na.rm=TRUE))) # because this is not a complete tiling then many particles are lost
# migr gives the proportion of particles arriving in the receiver that come from the source
# the column sums are all 1 
sapply(migr, function(x) range(apply(x,2,sum,na.rm=TRUE))) # this is correct
```


```{r}
marlborough <- read.csv("data/marlborough.csv")
plot(coast.marlselect$geometry, col="dark green", xlim=xlim.marlselect, ylim=ylim.marlselect); box()
rect(xlim.marlselect[1], ylim.marlselect[1], xlim.marlselect[2], ylim.marlselect[2])
points(marlborough$x, marlborough$y, pch=16, col="red", cex=0.4)
#box(); axis(1); axis(2)
```


