# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hello world function, this time in C
#'
#' @description Just getting going
#'
#' @export
rcpp_hello_world <- function() {
    .Call(`_algae_rcpp_hello_world`)
}

#' Test function - multiply by 2
#'
#' @description Just testing
#'
#' @export
timesTwo <- function(x) {
    .Call(`_algae_timesTwo`, x)
}

#' @title Create mean matrix mumat
#'
#' @description Create the mean matrix mumat
#'
#' @export
rcpp_make_mumat <- function(parlist, cpar) {
    .Call(`_algae_rcpp_make_mumat`, parlist, cpar)
}

