# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hello world function, this time in C
#'
#' @description Just getting going
#'
#' @export
rcpp_hello_world <- function() {
    .Call(`_algae_rcpp_hello_world`)
}

